### ISSUE TITLE
DEFUNCT process on Unix systems not registered during pruning

### ISSUE THREAD

**Issue by mdsauce** [maxdobeck/sauced#20]
If you `kill -SIGINT some-tunnel-pid` the tunnel doesn't register the sigint.  In a brief test 1 tunnel did close and we went from 5 to 4 but nothing was logged locally.

**Comment by maxdobeck** [comment]
https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed

Defunct process isn't detected as such by the parent process:
`2846  0.3  0.0      0     0 pts/1    Z+   17:15   0:01 [sc] <defunct>`
because the parent process is still around we have to check for defunct processes.

**Comment by maxdobeck** [comment]
Added `defer scCmd.Wait()` in tunnel_unix.go.  Should take care of the problem on non-windows systems I think.
